'use strict'

/**
 * Package entry point.
 *
 * Delegates to the generated index.js, and turns the one failure mode this
 * distribution model introduces — the install script never ran, so the binary
 * was never downloaded — into an error that says what to do about it.
 *
 * index.js is generated by napi-rs and must stay untouched; CI asserts it
 * matches `napi build` output. All of the handling lives here instead.
 */

const fs = require('node:fs')
const path = require('node:path')

const { BINARY_NAME, REPO, SUPPORTED, detectTriple, binaryFileName } = require('./platform.js')
const { version } = require('./package.json')

const RELEASE_URL = `https://github.com/${REPO}/releases/tag/v${version}`

/**
 * How the consumer installed us, so the fix we lead with is the one they can
 * actually apply. Best-effort: an unrecognised layout falls back to npm.
 */
function detectPackageManager() {
  if (process.versions.pnp) {
    return 'yarn-pnp'
  }
  if (__dirname.split(path.sep).includes('.pnpm')) {
    return 'pnpm'
  }
  if (__dirname.includes(`.yarn${path.sep}`)) {
    return 'yarn'
  }
  return 'npm'
}

const FIXES = {
  pnpm: [
    '  pnpm 10 and newer block dependency install scripts by default.',
    '  Allow this package to run its one script:',
    '',
    '      pnpm approve-builds',
    '',
    '  or declare it in pnpm-workspace.yaml (pnpm 10+) or package.json:',
    '',
    '      onlyBuiltDependencies:',
    `        - ${BINARY_NAME}`,
    '',
    '  then reinstall:',
    '',
    '      pnpm install',
  ],
  'yarn-pnp': [
    '  Yarn PnP does not run install scripts unless the package opts in.',
    '  Add this to your package.json and reinstall:',
    '',
    '      "dependenciesMeta": {',
    `        "${BINARY_NAME}": { "built": true }`,
    '      }',
  ],
  yarn: [
    '  Yarn may have been configured to skip install scripts. Re-enable them:',
    '',
    '      yarn config set enableScripts true',
    '      yarn install',
  ],
  npm: [
    '  This usually means the install ran with --ignore-scripts.',
    '  Reinstall without it:',
    '',
    `      npm install ${BINARY_NAME}`,
    '',
    '  If your project sets it globally, check:',
    '',
    '      npm config get ignore-scripts',
  ],
}

function missingBinaryMessage(file) {
  return [
    '',
    `  ${BINARY_NAME} could not load its native binary (${file}).`,
    '',
    `  ${BINARY_NAME} publishes a single npm package and downloads the binary for`,
    '  your platform from GitHub during install. That download runs as an install',
    '  script, and it looks like the script never ran.',
    '',
    ...FIXES[detectPackageManager()],
    '',
    '  ---',
    '',
    '  Already allowed scripts? Run the download directly:',
    '',
    `      node node_modules/${BINARY_NAME}/postinstall.js`,
    '',
    '  No network during install? Download the binary once,',
    '',
    `      ${RELEASE_URL}`,
    '',
    '  and point at it:',
    '',
    `      export NAPI_RS_NATIVE_LIBRARY_PATH=/path/to/${file}`,
    '',
  ].join('\n')
}

function unsupportedPlatformMessage() {
  return [
    '',
    `  ${BINARY_NAME} does not ship a prebuilt binary for ${process.platform}-${process.arch}.`,
    '',
    '  Prebuilt targets:',
    ...SUPPORTED.map((target) => `      ${target}`),
    '',
    '  To run here, build the addon from source and point at the result:',
    '',
    `      git clone https://github.com/${REPO}`,
    '      cd xirr-rs && npm install && npx napi build --platform --release',
    `      export NAPI_RS_NATIVE_LIBRARY_PATH=/path/to/${BINARY_NAME}.<platform>.node`,
    '',
  ].join('\n')
}

try {
  module.exports = require('./index.js')
} catch (loadError) {
  const triple = detectTriple()

  // An unsupported platform is a different problem from a blocked install
  // script, and the advice for it is different too.
  if (!triple) {
    const error = new Error(unsupportedPlatformMessage())
    error.cause = loadError
    throw error
  }

  const file = binaryFileName()

  // If the binary is on disk, the install worked and the load failed for some
  // other reason — a glibc too old for the build, a corrupt file, SELinux.
  // Say so rather than sending them off to fix an install script that ran fine.
  if (fs.existsSync(path.join(__dirname, file))) {
    throw loadError
  }

  const error = new Error(missingBinaryMessage(file))
  error.cause = loadError
  throw error
}
