/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Number of sign changes in the cash flow. Zero or one guarantees a unique
 * root in (-1, inf) by Descartes' rule, so no policy question arises.
 */
export declare function signChanges(amounts: Float64Array): number

/**
 * Internal rate of return for an irregular schedule.
 *
 * Returns the same rate Excel, Google Sheets and LibreOffice Calc return,
 * including which root is chosen when several exist. Returns `null` where
 * those engines return #NUM! and no root can be found.
 */
export declare function xirr(dates: Float64Array, amounts: Float64Array, guess?: number | undefined | null, dayCountConvention?: string | undefined | null, policy?: 'spreadsheetThenRobust' | 'spreadsheet' | 'lowest' | 'closestToGuess'): number | null

/**
 * Every rate at which XNPV crosses zero, ascending.
 *
 * A length greater than one means the IRR is genuinely ambiguous and the
 * single value returned by `xirr` is a convention, not a fact. Surface this
 * in reporting rather than hiding it.
 */
export declare function xirrAllRoots(dates: Float64Array, amounts: Float64Array, dayCountConvention?: string | undefined | null): Array<number>

/**
 * Net present value of an irregular schedule at a given rate.
 * Use with `xirr` to check the residual of whatever rate you were handed.
 */
export declare function xnpv(rate: number, dates: Float64Array, amounts: Float64Array, dayCountConvention?: string | undefined | null): number
