/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The result of a solve, with every non-answer named.
 *
 * | `status`              | `rate`   | meaning                                          |
 * | --------------------- | -------- | ------------------------------------------------ |
 * | `root`                | the rate | one rate solves the cash flow                    |
 * | `multipleRoots`       | the pick | several do; `roots` lists them all                |
 * | `noRootExists`        | `null`   | **proved**: no rate can solve this cash flow      |
 * | `didNotConverge`      | `null`   | a root may exist; the solver did not produce one  |
 * | `spreadsheetNumError` | `null`   | `#NUM!` reproduced under the `spreadsheet` policy |
 *
 * The last three were a single `null` before this release, which meant a
 * caller could not tell a data-quality problem in their own ledger from a
 * solver failure from a faithfully reproduced spreadsheet error.
 */
export interface XirrResult {
  status: 'root' | 'multipleRoots' | 'noRootExists' | 'didNotConverge' | 'spreadsheetNumError'
  /** The rate, or `null` for every failure status. Never `NaN`. */
  rate?: number
  /**
   * Every root found, ascending. Empty for every failure status. A length
   * above one means the IRR is genuinely ambiguous and `rate` is a
   * convention, not a fact.
   */
  roots: Array<number>
}

/**
 * Number of sign changes in the **date-netted** cash flow.
 *
 * Breaking change: this used to take only the amounts, which meant it could
 * not net payments sharing a date and could not order them. Both defects
 * changed the answer.
 *
 * Zero proves no root exists; one proves exactly one root exists; any odd
 * number proves at least one exists. An even number above zero proves nothing
 * either way.
 */
export declare function signChanges(dates: Float64Array, amounts: Float64Array, dayCountConvention?: string | undefined | null): number

/**
 * Internal rate of return for an irregular schedule.
 *
 * Returns the same rate Excel, Google Sheets and LibreOffice Calc return,
 * including which root is chosen when several exist, and additionally answers
 * cash flows those engines give up on.
 *
 * Breaking change: this used to return `number | null`. It now returns a
 * `XirrResult`, so that "no rate exists" and "no rate was found" are
 * distinguishable. For the old shape use `xirrRate`, or read `.rate`.
 */
export declare function xirr(dates: Float64Array, amounts: Float64Array, guess?: number | undefined | null, dayCountConvention?: string | undefined | null, policy?: 'spreadsheetThenRobust' | 'spreadsheet' | 'lowest' | 'closestToGuess'): XirrResult

/**
 * The rate alone, or `null` if there is not one.
 *
 * The lossy convenience form of `xirr`: it cannot tell you *why* there is no
 * rate. Prefer `xirr` anywhere that distinction has to reach a human or a
 * ledger.
 */
export declare function xirrRate(dates: Float64Array, amounts: Float64Array, guess?: number | undefined | null, dayCountConvention?: string | undefined | null, policy?: 'spreadsheetThenRobust' | 'spreadsheet' | 'lowest' | 'closestToGuess'): number | null

/**
 * Every rate at which XNPV crosses zero, ascending.
 *
 * A length greater than one means the IRR is genuinely ambiguous and the
 * single value returned by `xirr` is a convention, not a fact. Surface this
 * in reporting rather than hiding it.
 */
export declare function xirrAllRoots(dates: Float64Array, amounts: Float64Array, dayCountConvention?: string | undefined | null): Array<number>

/**
 * Net present value of an irregular schedule at a given rate.
 * Use with `xirr` to check the residual of whatever rate you were handed.
 */
export declare function xnpv(rate: number, dates: Float64Array, amounts: Float64Array, dayCountConvention?: string | undefined | null): number
