/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function xirr(dates: Float64Array, amounts: Float64Array, guess?: number | undefined | null, dayCountConvention?: string | undefined | null): number | null
